### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rahul286** [rubygems/rubygems-mirror#13]
Please add in README that 'gem mirror' will need more than 50GB on harddrive!

I ran it on my production server. 
It used my all disk space, which crashed my database server!

Anyway, thanks for this "gem" :-)

**Comment by raggi** [comment]
We do have community mirrors now, and most of them are (or at least were, when I was last involved at all), using nginx lazy mirroring.

**Comment by raggi** [comment]
As far as documenting the size, sure, send a PR, but the size is very different now to when the issue was opened.
