### ISSUE TITLE
gem mirror command doesn't continue from where it left off, if command was aborted

### ISSUE THREAD

**Issue by praste** [rubygems/rubygems-mirror#22]
I ran command "gem mirror" to mirror rubygems but it got aborted after downloading about 10K gems due to error "too many connection resets"

I then tried to re-run "gem mirror" command hoping it would continue from where it left off. I  kept getting same error "too many connection resets". I had to delete destination directory and start agin and I went into an infinite loop

**Comment by alexander-tsig** [comment]
ERROR:  While executing gem ... (Net::HTTP::Persistent::Error)
    too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 769 requests on 70261625619240, last used 7.926816 seconds ago
