### ISSUE TITLE
version 1.0.1 don't mirror /quick directory

### ISSUE THREAD

**Issue by kfirlavi** [rubygems/rubygems-mirror#31]
Hi,
the repository has the changes but the gem at rubygems is not mirroring the quick directory. 
I have merged the diff to my working code, and it is mirroring the /quick.
Now I can serve the gems. 
Please release new version with the changes in the git repository.

Regards,
Kfir

**Comment by facastagnini** [comment]
I run into the same problem today. I find out that the master code does mirror the /quick directory, then the problem is that we need a new release of the rubygems-mirror gem...

@raggi can you please create a new release? Thanks a lot!

**Comment by raggi** [comment]
Done

**Comment by facastagnini** [comment]
Thanks man
