### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xor256** [rubygems/rubygems-mirror#69]
gem mirror
/usr/lib64/gems/ruby/psych-3.1.0/psych.so: warning: already initialized constant Psych::Parser::ANY
/usr/lib64/gems/ruby/psych-3.1.0/psych.so: warning: already initialized constant Psych::Parser::UTF8
/usr/lib64/gems/ruby/psych-3.1.0/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/usr/lib64/gems/ruby/psych-3.1.0/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/usr/share/ruby/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
/usr/share/ruby/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
/usr/share/ruby/psych/class_loader.rb:9: warning: previous definition of DATE was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/usr/share/ruby/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
/usr/share/ruby/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT
/usr/share/ruby/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
/usr/share/ruby/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
/usr/share/ruby/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE
/usr/share/ruby/psych/class_loader.rb:15: warning: previous definition of RANGE was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL
/usr/share/ruby/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
/usr/share/ruby/psych/class_loader.rb:17: warning: previous definition of REGEXP was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT
/usr/share/ruby/psych/class_loader.rb:18: warning: previous definition of STRUCT was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL
/usr/share/ruby/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE
/usr/share/ruby/psych/class_loader.rb:65: warning: previous definition of CACHE was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME
/usr/share/ruby/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT
/usr/share/ruby/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
/usr/share/ruby/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY
/usr/share/ruby/psych/nodes/stream.rb:13: warning: previous definition of ANY was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8
/usr/share/ruby/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
/usr/share/ruby/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
/usr/share/ruby/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY
/usr/share/ruby/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
/usr/share/ruby/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/usr/share/ruby/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
/usr/share/ruby/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/usr/share/ruby/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
/usr/share/ruby/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/usr/share/ruby/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
/usr/share/ruby/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/usr/share/ruby/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY
/usr/share/ruby/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/usr/share/ruby/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/usr/share/ruby/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
/usr/share/ruby/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/visitors/to_ruby.rb:336: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
/usr/share/ruby/psych/visitors/to_ruby.rb:336: warning: previous definition of SHOVEL was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS
/usr/share/ruby/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/usr/share/gems/gems/psych-3.1.0/lib/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/usr/share/ruby/psych/handler.rb:30: warning: previous definition of EVENTS was here
Traceback (most recent call last):
	14: from /usr/bin/gem:21:in `<main>'
	13: from /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:44:in `run'
	12: from /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:79:in `do_configuration'
	11: from /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:79:in `new'
	10: from /usr/local/share/ruby/site_ruby/rubygems/config_file.rb:182:in `initialize'
	 9: from /usr/local/share/ruby/site_ruby/rubygems/config_file.rb:332:in `load_file'
	 8: from /usr/local/share/ruby/site_ruby/rubygems.rb:698:in `load_yaml'
	 7: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /usr/share/gems/gems/psych-3.1.0/lib/psych.rb:20:in `<top (required)>'
	 4: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:72:in `require'
	 3: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /usr/share/gems/gems/psych-3.1.0/lib/psych/parser.rb:2:in `<top (required)>'
	 1: from /usr/share/gems/gems/psych-3.1.0/lib/psych/parser.rb:33:in `<module:Psych>'
/usr/share/gems/gems/psych-3.1.0/lib/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)

on fedora

**Comment by hsbt** [comment]
This error is not related `gem server` command.
