### ISSUE TITLE
There's no documentation

### ISSUE THREAD

**Issue by ctgswallow** [rubygems/rubygems-mirror#9]
The wiki has nothing, the link to the documentation site doesn't work, and there is hardly any documentation otherwise.

**Comment by facastagnini** [comment]
Check #38

**Comment by raggi** [comment]
The code isn't long, I'd strongly recommend reading it.

I realize this isn't documentation, but the README is half the length of the entire implementation right now (test_setup.rb excluded)

**Comment by zenspider** [comment]
Please close. Between the readme and `gem mirror --help` this doesn't seem true anymore.
